### ISSUE TITLE
Not able to build the UI

### ISSUE THREAD

**Issue by Cuoremort** [TareHimself/manga-translator#15]
Every time I try to run the poe command to build the ui I get this error.

Poe => npm install && npm run build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\-----\MangaTranslator\manga-translator/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\-----\MangaTranslator\manga-translator\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by TareHimself** [comment]
Are you running commands from the actual repo or from a folder outside it?

**Comment by Lazorox** [comment]
If you still run into this problem run:
npm init
and create a package.json file. Just press ENTER until the file is created

**Comment by TareHimself** [comment]
actually, that will create more problems, the solution now is to pull, then install. I forgot to push the package.json
