### ISSUE TITLE
The Script "build" seems to be missing

### ISSUE THREAD

**Issue by Lazorox** [TareHimself/manga-translator#16]
Every time I try to execute "poe build-ui" I get the following problem:

(manga-translator) C:\Users\lazorox\Desktop\mangalol\manga-translator>poe build-ui
Poe => npm install && npm run build

up to date, audited 1 package in 445ms

found 0 vulnerabilities
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\lazorox\AppData\Local\npm-cache\_logs\2023-08-26T21_30_46_104Z-debug-0.log

**Comment by Lazorox** [comment]
If you can please explain how to use: 
python main.py -m [live|convert -f "files"]
like how can I translate the raw manga images. I tried to replace "files" with the path of a raw manga image but it didn't work.


Also the modules that I installed where should they be, I just moved them to the work folder.
In the install instructions it just says that I should install the modules.

Thx

**Comment by TareHimself** [comment]
Ah, I am dumb, I forgot to remove a git ignore that ignored the package.json. should be fixed now

**Comment by TareHimself** [comment]
```bash
usage: Manga Translator [-h] -m {live,convert} [-f FILES [FILES ...]] [-o OCR] [-oa OCR_ARGS] [-t TRA] [-ta TRA_ARGS]

Translates Manga Chapters

optional arguments:
  -h, --help            show this help message and exit
  -m {live,convert}, --mode {live,convert}
                        What mode to run
  -f FILES [FILES ...], --files FILES [FILES ...]
                        A list of images to convert or path to a folder of images
  -o OCR, --ocr OCR     Set the index of the ocr class to use. must be one of the following
                        0) BaseOcr => Always outputs "Sample"
                        1) CleanOcr => Cleans The Image i.e. does nothing
                        2) MangaOcr => Only Supports Japanese
                        3) EasyOcr => Supports all the languages listed
                        4) TesseractOcr => Supports all the languages listed
  -oa OCR_ARGS, --ocr-args OCR_ARGS
                        Set ocr class args i.e. 'key=value , key2=value'
  -t TRA, --tra TRA     Set the index of the translator class to use. must be one of the following
                        0) Translator => Base Class for all Translator classes
                        1) DeepLTranslator => The Best but it requires an auth token from here https://www.deepl.com/translator
                        2) GoogleTranslateTranslator => Translates using Google Translate
                        3) HuggingFace => Translates using hugging face models
                        4) DebugTranslator => Writes the specified text
  -ta TRA_ARGS, --tra-args TRA_ARGS
                        Set translator class args i.e. 'key=value , key2=value'
```

An example would be `python main.py --mode convert --files "file a" "file b" "file c" `
or `python main.py --mode convert --files "folder path `
