### ISSUE TITLE
Batch Translation and CLI Command

### ISSUE THREAD

**Issue by dfaizaditya** [TareHimself/manga-translator#31]
Hello thank you for your response earlier. The program works like a charm on the GUI.
But i have another question on the CLI part, the project seems to support batch translation so i placed the image needed for translation in the ./img folder in the same level as main.py

python main.py -f /img

is this how i should do it? can you provide an example of CLI of batch translation?

also the -m of the example doest seems right because its an unrecognizible command
python main.py -m -f image1.png image2.png

Thank you

**Comment by dfaizaditya** [comment]
Seems like i cant using the CLI properly am i missing something?
**python main.py -o 1 -f 005.jpg**
![Screenshot from 2023-12-23 00-06-15](https://github.com/TareHimself/manga-translator/assets/49333082/a46353cf-f170-498a-a818-d0f7dd8f7042)

**Comment by TareHimself** [comment]
Thanks for pointing this out, working on a fix now

**Comment by TareHimself** [comment]
So I have fixed this but I need to train a new color detection model before I update the main branch, you can pull the fix from the dev branch

**Comment by TareHimself** [comment]
updated
