### ISSUE TITLE
folder not found to install manga-translator

### ISSUE THREAD

**Issue by shubhamsd0027** [TareHimself/manga-translator#33]
(manga-translator) PS C:\Users\shubh\project000\manga-translator-master> poetry install
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

No dependencies to install or update

Installing the current project: manga-translator (0.1.0)
The current project could not be installed: No file/folder found for package manga-translator
If you do not want to install the current project use --no-root

I am getting this error while installing poetry in the manga-translator folder( initially cloned ) Also please elaborate more how to use node.js for UI

**Comment by qwertworm** [comment]
did you find a fix or did you just give up? I am facing same issue

**Comment by TareHimself** [comment]
Is this still happening with the latest version of the repo ?

**Comment by TareHimself** [comment]
Actually working on this now. Also, The UI is now prebuilt and pushed with the repo so you no longer require a node. just run `poe run-server`

**Comment by TareHimself** [comment]
Fixed
