### ISSUE TITLE
Add fallback fonts to drawers? 🤔

### ISSUE THREAD

**Issue by selfkilla666** [TareHimself/manga-translator#37]
Perhaps in text renderers it would be worth adding a parameter with fallback fonts, so that in case if not found some of them? This could help to add translations into Cyrillic or other languages that may not be supported in the current ones.

**Comment by TareHimself** [comment]
The fonts are stored [here](https://github.com/TareHimself/manga-translator/tree/master/fonts) so to you would just need to add the font you need to that folder for it to appear on the list , or are you suggesting a parameter that allows you to give it a path to a font ?
