### ISSUE TITLE
ModuleNotFoundError: No module named 'hyphenator'

### ISSUE THREAD

**Issue by ShaunFell** [TareHimself/manga-translator#38]
I ran install as detailed in the ReadMe. But when I run the script, I get the error

```
ModuleNotFoundError: No module named 'hyphenator'
```

If I run pip install hyphenator, then rerun the script I get the error

```
FileNotFoundError: [Errno 2] No such file or directory: 'en_US'
```

**Comment by TareHimself** [comment]
Are you getting this error on the latest tag ?

**Comment by ShaunFell** [comment]
I downloaded the latest release again and ran main.py with same result. 

> Traceback (most recent call last):
  File "/home/<user>/Documents/Computer/Software/manga-translator/manga-translator-2024.01.31/main.py", line 8, in <module>
    from translator.pipelines import FullConversion
  File "/home/<user>/Documents/Computer/Software/manga-translator/manga-translator-2024.01.31/translator/pipelines.py", line 6, in <module>
    from translator.utils import (
  File "/home/<user>/Documents/Computer/Software/manga-translator/manga-translator-2024.01.31/translator/utils.py", line 20, in <module>
    from hyphen import Hyphenator
ImportError: cannot import name 'Hyphenator' from 'hyphen' (/home/<user>/.local/lib/python3.12/site-packages/hyphen/__init__.py)

**Comment by ShaunFell** [comment]
Hi, sorry for the late response. Yes, I cloned the repo again, started a new conda enviro and did peotry  install, exactly as in the readme, but the same result

**Comment by TareHimself** [comment]
Can I see the install output ?

**Comment by ShaunFell** [comment]
[out.txt](https://github.com/TareHimself/manga-translator/files/14806566/out.txt)

heres the output of 
`poetry install -vvv`

**Comment by JohnKirk1337** [comment]
Same for me, but it fails at PySimpleGUI
![image](https://github.com/user-attachments/assets/c1ff16b7-04e2-4c4c-89ff-0bd1d691278b)

**Comment by TareHimself** [comment]
This should be fixed in the latest version on master
