### ISSUE TITLE
Where is the poe cmdlet so i can add it to PATH, I cant find anything online about it

### ISSUE THREAD

**Issue by samir-a-ali** [TareHimself/manga-translator#39]
poe : The term 'poe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ poe force-cuda
+ ~~~
    + CategoryInfo          : ObjectNotFound: (poe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by TareHimself** [comment]
poe is a package that works with poetry, if you have poetry installed and have installed dependencies it should work

**Comment by qwertworm** [comment]
I just don't get it. What am I doing wrong ? Warning: The current project could not be installed: [Errno 2] No such file or directory: 'C:\\Users\\qwertworm\\README.md'
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
I did ceate the system variable for conda so what is this error? I did all the steps in order but this is the error I get when typing the command poetry install
